FROM mysql:latest

MAINTAINER "Alvin Teh" <i@alvinteh.me>

ENV MYSQL_DATABASE test
ENV MYSQL_ROOT_PASSWORD username1

# Ensure the following script has its permissions set to 755
CMD ["/var/www/etc/init.sh"]
